# Generated by Django 5.2 on 2026-06-04 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='applications.application')),
                ('reviewer', models.ForeignKey(limit_choices_to={'role': 'reviewer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review Assignment',
                'verbose_name_plural': 'Review Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('application', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('recommendation', models.CharField(choices=[('recommend', 'Recommend'), ('reject', 'Reject'), ('hold', 'Hold for Later'), ('neutral', 'No Recommendation')], default='neutral', max_length=20)),
                ('is_final', models.BooleanField(default=False, help_text='Mark this as the final recommendation for this assignment.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reviews.reviewassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
